# https://taskfile.dev
version: "3"

includes:
  #docs: ./tasks/Taskfile.docs.yml
  docs:
    taskfile: ./website
    dir: website

tasks:
  default:
    silent: true
    cmds:
      - echo "Welcome to Wingnut"
      - task -l