# https://taskfile.dev
version: "3"

includes:
  code: ./tasks/Taskfile.go.yml
  setup: ./tasks/Taskfile.setup.yml
  docs:
    taskfile: ./website
    dir: website

tasks:
  default:
    silent: true
    cmds:
      - echo "Welcome to Wingnut"
      - task -l