# https://taskfile.dev

version: '3'

silent: true

tasks:
  clean:
    desc: "Run 'go mod tidy'"
    silent: true
    cmds:
      - go mod tidy

  format:
    desc: gofumpt all go code
    cmds:
      - gofumpt -w -l .
