# https://taskfile.dev

version: '3'

silent: true

tasks:
  install:
    desc: "Install Docusaurus locally using Yarn"
    silent: true
    dir: website
    cmds:
      - yarn install

  serve:
    desc: "Run local dev server to preview the docs"
    silent: true
    dir: website
    cmds:
      - yarn start

  build:
    desc: "Build the docs website"
    silent: true
    dir: website
    cmds:
      - yarn build